/*
 *     Copyright (C) 2024 Valeri Gokadze
 *
 *     shrayesh_patro is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     shrayesh_patro is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 *
 *     For more information about shrayesh_patro, including how to contribute,
 *     please visit: https://github.com/bhupendra/shrayesh_patro
 */

List albumsDB = [
  {
    'ytid': 'PLinVjP-aRmluMwA11p_McSjhLuPhllk6r',
    'title': 'Hindi Hits',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/1.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLinVjP-aRmluGBNQgXtFHbsMHEpi5nsDK',
    'title': 'Hindi',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/2.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLinVjP-aRmlsqviDrpzc4NxjH76mbU_BD',
    'title': 'Best Hindi',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/3.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLinVjP-aRmlsOWjxcabE_wa5i2qcD7qrY',
    'title': 'Romance',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/4.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLinVjP-aRmltCF0bpPnr0epOMseexUBcy',
    'title': "Hindi Hits Super",
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/5.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLinVjP-aRmlss98fP0D5pVapLEZakyGgw',
    'title': 'Hits Songs',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/6.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLM3TSQaW_spO4-9GyvJb4Ngtc1BhNQNwX',
    'title': 'Hindi',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/7.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLQlb0UatjMVbIu9ioDGNwgpL47swu6kv2',
    'title': 'Swati Mishra Bhakti',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/8.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLQlb0UatjMVZ6Hf89visMyOiFiY3kQqlV',
    'title': 'Swati Mishra',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/9.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLQlb0UatjMVYRBsTuIA9RcfJauhhLwwDc',
    'title': 'Swati Mishra Bhakti',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/10.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLQlb0UatjMVadE-l_xty1hfhyLki7uXBb',
    'title': 'Swati Mishra Bhakti',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/11.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL9bw4S5ePsEEy5C3XCKyBXLaB3TSyc3rP',
    'title': "Hinndi",
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/12.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL9bw4S5ePsEFAfCoWq16pRDYD9UwN9UTW',
    'title': "best bhajan",
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/13.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL9bw4S5ePsEFhtP3nt4lK3S8YhVd8UJ6o',
    'title': 'Hindi Songs',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/14.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL9bw4S5ePsEGhPJMxZV3MfDMIWCyACpo4',
    'title': 'Hindi',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/15.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL9bw4S5ePsEFfBBeNR20hFtlJUOCOgirP',
    'title': 'Laapataa Ladies',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/16.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL9bw4S5ePsEGgFDKcJYBfU4gBirqHzboS',
    'title': 'Pankaj Udhas Mix',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/17.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL9bw4S5ePsEFgGsjeaUGjFjvxnMmj1CFT',
    'title': "Unplugged Series | Bollywood",
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/18.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL9bw4S5ePsEGoD6YLv_nSSmqokgmN2F2S',
    'title': 'Salman Khan Hits',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/19.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL9bw4S5ePsEE0jGfUgUMvzeWAaMPcqHL9',
    'title': 'Hindi Bhakti Songs',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/20.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL9bw4S5ePsEGq3PMGDWs2GRK4uSLOTIMl',
    'title': 'Bhajans | Krishna',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/21.png',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL9bw4S5ePsEHQgIz9PZDSmGXoE9aMBCqH',
    'title': 'Tulsi Kumar Bhajans',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/22.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PL9bw4S5ePsEFsrgkpxx-58ItZrTz4ZyAm',
    'title': 'Shivratri Special',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/23.png',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLfJBvoNea3pGrk_Hg3jodqIZl1zh_LvGJ',
    'title': 'Arun Thapa Songs',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/24.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLfJBvoNea3pFGj9R8goKhc415guGb9aXT',
    'title': 'Favorite Five',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/25.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLfJBvoNea3pFGJwwo-_Jkf6IsUdDYM3Xq',
    'title': 'Music Dot Com | Hit',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/26.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLfJBvoNea3pFf4naavrxNbUJvNm47DjgA',
    'title': 'Yam Baral Songs',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/27.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLfJBvoNea3pHbFmp35HmmTMwHY5MH2CK7',
    'title': '2019 Hits',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/28.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLfJBvoNea3pGVmuQ7Nr7V8_VdGp68K62m',
    'title': 'Melody Hits',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/29.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLfJBvoNea3pEBkRK-SfZ1Wi0fkYVLQKiW',
    'title': '2017 Superhit Songs',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/30.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLXCoHsJ9oLefSBV4aF7gTj3Rs9_HvubEJ',
    'title': 'Stree 2 | Shraddha Kapoor |',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/31.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLXCoHsJ9oLee87DItlNWSw2R7VAkTcq5q',
    'title': 'Top Hindi Songs',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/32.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLXCoHsJ9oLefLO2qXLfLhVIiBomnu5Ags',
    'title': 'Bad Newz | Vicky',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/33.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLXCoHsJ9oLefaEE8QWrQfgNnewQ0aqvKH',
    'title': 'Saregama Music',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/34.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLXCoHsJ9oLech1h6ktvB8Cc6dCV_z-4ii',
    'title': 'New Year Party Playlist',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/35.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLXCoHsJ9oLefBprn38xyDfvgL-73WncT9',
    'title': 'Rocky Aur Rani Kii',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/36.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLfJBvoNea3pFMYIubgXfJ4JvJqk7iRT1x',
    'title': 'Scorpion - Drake',
    'image': 'https://sgrayesh-dahal.github.io/bhupendra/pic/37.jpg',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mC1dIZC9-5x3XR2TJP-KpxiVaA_L_U9K8',
    'title': 'LOOK AT ME - XXXTENTACION',
    'image': 'https://i.scdn.co/image/ab67616d0000b27352cc5e3765a135c52e1bbbbc',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_m5riLsB5iVpADmWfHmzkFNc8QGBWwBkWM',
    'title': 'SKINS - XXXTENTACION',
    'image': 'https://i.scdn.co/image/ab67616d0000b273da9e59639a9759d8952890c6',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lqRFvHXwqV_C6J-_ruobnyZgR2K6Ql8Qk',
    'title': '? - XXXTENTACION',
    'image': 'https://i.scdn.co/image/ab67616d0000b273806c160566580d6335d1f16c',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lkSMrwgF3m0BCgIA0v1G1VZhSscZg37cY',
    'title': 'The Show - Niall Horan',
    'image': 'https://i.scdn.co/image/ab67616d0000b2732a368fea49f5c489a9dc3949',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kq_gJdWJ9LUwgYzXMWeocvSyee4OqsvOQ',
    'title': 'Norman Fucking Rockwell! - Lana Del Rey',
    'image': 'https://i.scdn.co/image/ab67616d0000b273879e9318cb9f4e05ee552ac9',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lFbfW_UOra8dYRTa69lxR3fxYjogNtiQw',
    'title': 'THE TORTURED POETS DEPARTMENT - Taylor Swift',
    'image': 'https://i.scdn.co/image/ab67616d0000b2735076e4160d018e378f488c33',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_lVxq_QCXDlleCnpsszQyiFextilkX12_w',
    'title': "WE DON'T TRUST YOU - Future, Metro Boomin",
    'image': 'https://i.scdn.co/image/ab67616d00001e02a46b07c291e6dfdee13b3ee8',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kZqVnh5DXwZ95R5yuAnWUX20OjrNJh09U',
    'title': 'Fireworks & Rollerblades - Benson Boone',
    'image': 'https://i.scdn.co/image/ab67616d0000b273cc04ff3e70e146ba9abacf40',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mbcpEgHbfi3deQRnyGfQWnlzgQd86_tMI',
    'title': 'Wasteland, Baby! - Hozier',
    'image': 'https://i.scdn.co/image/ab67616d00001e025795e01c151ba5a8ce4bd295',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_mG42_gxfZ-Cq6Y921XWm43Z75YAiaSIWI',
    'title': 'eternal sunshine (slightly deluxe) - Ariana Grande',
    'image': 'https://i.scdn.co/image/ab67616d0000b273bd3de668e4784d791c4ab695',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kmtA2RV4sA_baCJwuaazeDtKmBM85j-yo',
    'title': 'UTOPIA - Travis Scott',
    'image': 'https://i.scdn.co/image/ab67616d00001e02881d8d8378cd01099babcd44',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kDuqdPyyBdToRV-mvWklRE_ysv7-LqveI',
    'title': 'One Thing At A Time - Morgan Wallen',
    'image': 'https://i.scdn.co/image/ab67616d0000b273705079df9a25a28b452c1fc9',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_kFa9tOyLsP4JH1EqSD3hIudVdkmQWfKT0',
    'title': 'DECIDE - Djo',
    'image': 'https://i.scdn.co/image/ab67616d0000b273fddfffec51b4580acae727c1',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_ngyCd9rAr-KZ5eI5juhaOe-LgrjlteONU',
    'title':
    'Hard To Imagine The Neighbourhood Ever Changing - The Neighbourhood',
    'image': 'https://i.scdn.co/image/ab67616d0000b2739b6ac98a52f62d5cb473da40',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'PLsCPTY_MPoPbEMmr8uZ7msRYcYtDz0g9g',
    'title': 'HIT ME HARD AND SOFT - Billie Eilish',
    'image': 'https://i.scdn.co/image/ab67616d0000b27371d62ea7ea8a5be92d3c1f62',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_m2MkFaiKAqsvU8RR3o1qAGMLkSCtIl8vU',
    'title': '12 Notes - Alec Benjamin',
    'image': 'https://i.scdn.co/image/ab67616d0000b27310937fa41a9718c72a59d85b',
    'isAlbum': true,
    'list': [],
  },
  {
    'ytid': 'OLAK5uy_nH6vZsFvVyJt06PcH5O9SXqV5lT3-I5hY',
    'title': 'Narrated For You - Alec Benjamin',
    'image': 'https://i.scdn.co/image/ab67616d0000b273459d675aa0b6f3b211357370',
    'isAlbum': true,
    'list': [],
  }
];
