name: shrayesh_patro
description: "A Music & Calendar App Developed by Bhupendra Dahal. Rajpurohit (Google Me)"
publish_to: "none"
version: 7.2.4+110 # run update.sh after changing the version

environment:
  sdk: ">=3.3.2 <4.0.0"
dependencies:
  audio_service: ^0.18.14
  audio_session: ^0.1.20
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.7.0
  file_picker: ^8.0.6
  fluentui_system_icons: ^1.1.246
  flutter:
    sdk: flutter
  flutter_flip_card: ^0.0.6
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^4.0.10
  html: ^0.15.4
  http: ^1.2.0
  intl: ^0.19.0
  just_audio: ^0.9.39
  path_provider: ^2.1.3
  rxdart: ^0.27.7
  url_launcher: ^6.3.0
  youtube_explode_dart: ^2.3.6
  device_info_plus: ^10.1.1
  flutter_markdown: ^0.7.3
  pub_semver: ^2.1.4
  fluent_ui: ^4.9.0
  google_fonts: ^6.2.1
  flutter_archive: ^6.0.3
  carousel_slider: ^4.2.1
  persistent_bottom_nav_bar_v2: ^5.3.0
  flutter_bloc: ^8.1.6
  shared_preferences: ^2.3.1
  equatable: ^2.0.5
  dio: ^5.7.0
  get_it: ^7.7.0
  dartz: ^0.10.1
  shimmer: ^3.0.0
  get: ^4.6.6
  flutter_tts: ^4.0.2
  connectivity_plus: ^6.0.4
  flutter_downloader: ^1.11.8
  permission_handler: ^11.3.1
  pointer_interceptor: ^0.10.1+2
  flutter_inappwebview: ^6.0.0
  nepali_utils:
    path: ./packages/nepali_utils
  material_design_icons_flutter: 5.0.5955-rc.1
  audiotagger: ^2.2.1
  metadata_god: ^0.5.2+1
  audioplayers: ^6.1.0
  html_unescape: ^2.0.0
  on_audio_query: ^2.9.0
  fluttertoast: ^8.0.9
  palette_generator: ^0.3.3+4
  flip_card: ^0.7.0
  salomon_bottom_bar: ^3.3.2
  flutter_lyric: ^2.0.4+6
  sliding_up_panel: ^2.0.0+1
  logging: ^1.2.0

  marquee: ^2.2.3
  flutter_displaymode: ^0.6.0
  sizer: ^2.0.15
dependency_overrides:
  fading_edge_scrollview: ^4.1.1
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  translations_cleaner: ^0.0.5

  # flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/licenses/
    - assets/images/

  fonts:
    - family: paytoneOne
      fonts:
        - asset: fonts/paytone/PaytoneOne-Regular.ttf

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/splash.png
  color_dark: '#151515'
  image_dark: assets/images/splash.png

  android_12:
    image: assets/images/splash.png
    icon_background_color: '#ffffff'
    image_dark: assets/images/splash.png
    icon_background_color_dark: '#151515'

flutter_launcher_icons:
  android: 'launcher_icon'
  adaptive_icon_background: '#191919'
  adaptive_icon_foreground: 'assets/images/ic_launcher_foreground.png'
  adaptive_icon_round: 'assets/images/ic_launcher_round.png'
  image_path: 'assets/images/ic_launcher.png'
